# Generated by Django 5.2.5 on 2025-08-25 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='colors',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='color', to='home.color'),
            preserve_default=False,
        ),
    ]
